server:
  port: 8888
#  tomcat:
    #tomcat初始化线程20
#    min-spare-threads: 20
    #tomcat最大线程100
#    max-threads: 100
  #超时时间是5000ms
#  connection-timeout: 5000
#配置服务器日志输出
logging:
  config: classpath:config/log-config.xml
beetl:
  templatesPath: views
beetlsql:
  daoSuffix: Dao
  sqlPath: mappings
  ds:
    a:
      basePackage: com.cyh.project.onedao
    b:
      basePackage: com.cyh.project.twodao
  mutiple:
    datasource: a,b
spring:
  profiles:
    active: dev


